apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: moodle-google-managed-certificate
  namespace: moodle
spec:
  domains:
    #- moodle.<your-lb-external-ip-address>.nip.io
    #- anything-you-want.<your-lb-external-ip-address>.nip.io
    - moodle.<YOUR-LB-EXTERNAL-IP>.nip.io