---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-filestore
spec:
  capacity:
    storage: 2.5Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  nfs:
    path: /moodleshare
    server: <YOUR-FILESTORE-INTERNAL-IP> # filestore's internal IP