apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-backendconfig
  namespace: moodle
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    type: HTTP
    requestPath: /
  logging:
    enable: true
    sampleRate: 0.1
  # to uncoment when a cloud armor security policy exists and you want to apply it to the LB
  # securityPolicy:
  #   name: "moodle-armor-policy"
  # to uncoment when you want to enable CDN
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
  #     queryStringBlacklist: ""
  #     queryStringWhitelist: ""
  # to uncoment when gke >= 1.23.3-gke.900
    # cacheMode: CACHE_ALL_STATIC
    # clientTtl: 3600
    # defaultTtl: 3600
  #   maxTtl: 86400